### Membuat Series dari sebuah List Python

In [ ]:
import pandas as pd

li = [1, 7, 2]
se = pd.Series(li)

print(se)

0    1
1    7
2    2
dtype: int64

### Mengakses elemen pada Series

In [ ]:
li = [1, 7, 2]
se = pd.Series(li)

print(se[0])

1

### Memberi label pada Series

In [ ]:
li = [1, 7, 2]
se = pd.Series(li, index = ['x', 'y', 'z'])

print(se['x'])

1

### Membuat Series dari Dictionary

In [ ]:
calories = {"day1": 420, "day2": 380, "day3": 390}
se = pd.Series(calories)

print(se)

day1    420
day2    380
day3    390
dtype: int64

### Membuat DataFrame

In [ ]:
import pandas as pd

df = pd.DataFrame(data= {"Nama" : ["Ahmad", "Joko", "Adi"],
                         "Umur": [12, 13, 15],
                         "Kelas": [6, 7, 8]})

In [ ]:
df.columns

Index(['Nama', 'Umur', 'Kelas'], dtype='object')

In [ ]:
df.columns.values[0] = "Nama Singkat"

In [ ]:
df

  Nama Singkat  Umur  Kelas
0        Ahmad    12      6
1         Joko    13      7
2          Adi    15      8

In [ ]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}


df = pd.DataFrame(data)
df

   calories  duration
0       420        50
1       380        40
2       390        45

### Mengakses elemen pada DataFrame

In [ ]:
# ILOC: Positional indexing
df.iloc[0:2, [0,1]]

   calories  duration
0       420        50
1       380        40

In [ ]:
df.iloc[0:2, 0:2]

   calories  duration
0       420        50
1       380        40

In [ ]:
df.iloc[:, 0:2]

   calories  duration
0       420        50
1       380        40
2       390        45

In [ ]:
# LOC: Label indexing
df.loc[0:2, :'calories']

   calories
0       420
1       380
2       390

In [ ]:
df.loc[0:2, ['calories', 'duration']]

   calories  duration
0       420        50
1       380        40
2       390        45

In [ ]:
df['calories'] # mengakses column

0    420
1    380
2    390
Name: calories, dtype: int64

In [ ]:
df['calories'][0] # mengakses column dan row

420

In [ ]:
df[['calories']] # mengakses column (menghasilkan DataFrame)

   calories
0       420
1       380
2       390

In [ ]:
df[['calories']].loc[[0, 1]] # mengakses column (menghasilkan DataFrame) lalu mengakses row (menghasilkan DataFrame)

   calories
0       420
1       380

### Memberi nama pada Index

In [ ]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ['day1', 'day2', 'day3'])
print(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45

In [ ]:
df

      calories  duration
day1       420        50
day2       380        40
day3       390        45

### Membaca File CSV dengan DataFrame

In [ ]:
df = pd.read_csv('./data.csv')
print(df)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [ ]:
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

### Melihat DataFrame

In [ ]:
df.head()

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [ ]:
df.tail()

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [ ]:
df.head(10)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7        45    104       134     253.3
8        30    109       133     195.1
9        60     98       124     269.0

In [ ]:
df.shape

(169, 4)

In [ ]:
df.dtypes

Duration      int64
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

### Membaca Informasi pada DataFrame

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

In [ ]:
df.describe()

         Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [ ]:
df['Calories'].mean(), df['Calories'].median(), df['Calories'].mode()[0]

(375.79024390243916, 318.6, 300.0)

In [ ]:
df.corr()

          Duration     Pulse  Maxpulse  Calories
Duration  1.000000 -0.155408  0.009403  0.922717
Pulse    -0.155408  1.000000  0.786535  0.025121
Maxpulse  0.009403  0.786535  1.000000  0.203813
Calories  0.922717  0.025121  0.203813  1.000000

### Membuat DataFrame

In [ ]:
import pandas as pd

df = pd.DataFrame(data= {"Nama" : ["Ahmad", "Joko", "Adi"],
                         "Umur": [12, 13, 15],
                         "Kelas": [6, 7, 8]})

In [ ]:
df.columns

Index(['Nama', 'Umur', 'Kelas'], dtype='object')

In [ ]:
df.columns.values[0] = "Nama Singkat"

In [ ]:
df

  Nama Singkat  Umur  Kelas
0        Ahmad    12      6
1         Joko    13      7
2          Adi    15      8

In [ ]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}


df = pd.DataFrame(data)
df

   calories  duration
0       420        50
1       380        40
2       390        45

### Mengakses elemen pada DataFrame

In [ ]:
# ILOC: Positional indexing
df.iloc[0:2, [0,1]]

   calories  duration
0       420        50
1       380        40

In [ ]:
df.iloc[0:2, 0:2]

   calories  duration
0       420        50
1       380        40

In [ ]:
df.iloc[:, 0:2]

   calories  duration
0       420        50
1       380        40
2       390        45

In [ ]:
# LOC: Label indexing
df.loc[0:2, :'calories']

   calories
0       420
1       380
2       390

In [ ]:
df.loc[0:2, ['calories', 'duration']]

   calories  duration
0       420        50
1       380        40
2       390        45

In [ ]:
df['calories'] # mengakses column

0    420
1    380
2    390
Name: calories, dtype: int64

In [ ]:
df['calories'][0] # mengakses column dan row

420

In [ ]:
df[['calories']] # mengakses column (menghasilkan DataFrame)

   calories
0       420
1       380
2       390

In [ ]:
df[['calories']].loc[[0, 1]] # mengakses column (menghasilkan DataFrame) lalu mengakses row (menghasilkan DataFrame)

   calories
0       420
1       380

### Memberi nama pada Index

In [ ]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ['day1', 'day2', 'day3'])
print(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45

In [ ]:
df

      calories  duration
day1       420        50
day2       380        40
day3       390        45

### Membaca File CSV dengan DataFrame

In [ ]:
df = pd.read_csv('./data.csv')
print(df)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [ ]:
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

### Melihat DataFrame

In [ ]:
df.head()

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [ ]:
df.tail()

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [ ]:
df.head(10)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7        45    104       134     253.3
8        30    109       133     195.1
9        60     98       124     269.0

In [ ]:
df.shape

(169, 4)

In [ ]:
df.dtypes

Duration      int64
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

### Membaca Informasi pada DataFrame

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

In [ ]:
df.describe()

         Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [ ]:
df['Calories'].mean(), df['Calories'].median(), df['Calories'].mode()[0]

(375.79024390243916, 318.6, 300.0)

In [ ]:
df.corr()

          Duration     Pulse  Maxpulse  Calories
Duration  1.000000 -0.155408  0.009403  0.922717
Pulse    -0.155408  1.000000  0.786535  0.025121
Maxpulse  0.009403  0.786535  1.000000  0.203813
Calories  0.922717  0.025121  0.203813  1.000000

---

## Menerapkan Filtering pada DataFrame

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('./dirty_data.csv')

In [ ]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
# ILOC: Positional indexing
df.iloc[0:2, [0,1]]

   Duration          Date
0        60  '2020/12/01'
1        60  '2020/12/02'

In [ ]:
# LOC: Label indexing
df.loc[0:2, ['Duration', 'Date']]

   Duration          Date
0        60  '2020/12/01'
1        60  '2020/12/02'
2        60  '2020/12/03'

In [ ]:
df_filtered = df.loc[df['Pulse'] > 110]

In [ ]:
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [ ]:
df_filtered

    Duration          Date  Pulse  Maxpulse  Calories
1         60  '2020/12/02'    117       145     479.0
4         45  '2020/12/05'    117       148     406.0
23        60  '2020/12/23'    130       101     300.0

In [ ]:
 df.loc[df['Pulse'] > 110, ['Maxpulse']]

    Maxpulse
1        145
4        148
23       101

In [ ]:
df_45_450 = df[df['Duration'].isin([45, 450])]

In [ ]:
df_45_450

    Duration          Date  Pulse  Maxpulse  Calories
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
7        450  '2020/12/08'    104       134     253.3
18        45  '2020/12/18'     90       112       NaN
20        45  '2020/12/20'     97       125     243.0
22        45           NaN    100       119     282.0
24        45  '2020/12/24'    105       132     246.0

In [ ]:
import numpy as np

condition1 = (df['Calories'] >= 400)
condition2 = (df['Pulse'] > 90)

In [ ]:
df.loc[np.where(condition1 & condition2)]

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
4        45  '2020/12/05'    117       148     406.0

## Menerapkan Sorting pada DataFrame

In [ ]:
df.sort_values(by=['Pulse'], ascending=False)

    Duration          Date  Pulse  Maxpulse  Calories
23        60  '2020/12/23'    130       101     300.0
4         45  '2020/12/05'    117       148     406.0
1         60  '2020/12/02'    117       145     479.0
0         60  '2020/12/01'    110       130     409.1
6         60  '2020/12/07'    110       136     374.0
3         45  '2020/12/04'    109       175     282.4
8         30  '2020/12/09'    109       133     195.1
21        60  '2020/12/21'    108       131     364.2
13        60  '2020/12/13'    106       128     345.3
24        45  '2020/12/24'    105       132     246.0
14        60  '2020/12/14'    104       132     379.3
7        450  '2020/12/08'    104       134     253.3
10        60  '2020/12/11'    103       147     329.3
28        60  '2020/12/28'    103       132       NaN
19        60  '2020/12/19'    103       123     323.0
2         60  '2020/12/03'    103       135     340.0
25        60  '2020/12/25'    102       126     334.5
30        60  '2020/12/30'    102       129     380.3
5         60  '2020/12/06'    102       127     300.0
11        60  '2020/12/12'    100       120     250.7
29        60  '2020/12/29'    100       132     280.0
17        60  '2020/12/17'    100       120     300.0
26        60      20201226    100       120     250.0
22        45           NaN    100       119     282.0
12        60  '2020/12/12'    100       120     250.7
16        60  '2020/12/16'     98       120     215.2
15        60  '2020/12/15'     98       123     275.0
9         60  '2020/12/10'     98       124     269.0
20        45  '2020/12/20'     97       125     243.0
27        60  '2020/12/27'     92       118     241.0
31        60  '2020/12/31'     92       115     243.0
18        45  '2020/12/18'     90       112       NaN

In [ ]:
df_sort = df.sort_values(by=['Calories'], ascending=True)

In [ ]:
df_sort.head()

    Duration          Date  Pulse  Maxpulse  Calories
8         30  '2020/12/09'    109       133     195.1
16        60  '2020/12/16'     98       120     215.2
27        60  '2020/12/27'     92       118     241.0
31        60  '2020/12/31'     92       115     243.0
20        45  '2020/12/20'     97       125     243.0

## Menerapkan Mutating pada DataFrame

In [ ]:
df['Level'] = np.where(df['Maxpulse'] > 130, 'High', 'Low')

In [ ]:
df.head()

   Duration          Date  Pulse  Maxpulse  Calories Level
0        60  '2020/12/01'    110       130     409.1   Low
1        60  '2020/12/02'    117       145     479.0  High
2        60  '2020/12/03'    103       135     340.0  High
3        45  '2020/12/04'    109       175     282.4  High
4        45  '2020/12/05'    117       148     406.0  High

In [ ]:
df['Year'] = np.array('2020')

In [ ]:
df

    Duration          Date  Pulse  Maxpulse  Calories Level  Year
0         60  '2020/12/01'    110       130     409.1   Low  2020
1         60  '2020/12/02'    117       145     479.0  High  2020
2         60  '2020/12/03'    103       135     340.0  High  2020
3         45  '2020/12/04'    109       175     282.4  High  2020
4         45  '2020/12/05'    117       148     406.0  High  2020
5         60  '2020/12/06'    102       127     300.0   Low  2020
6         60  '2020/12/07'    110       136     374.0  High  2020
7        450  '2020/12/08'    104       134     253.3  High  2020
8         30  '2020/12/09'    109       133     195.1  High  2020
9         60  '2020/12/10'     98       124     269.0   Low  2020
10        60  '2020/12/11'    103       147     329.3  High  2020
11        60  '2020/12/12'    100       120     250.7   Low  2020
12        60  '2020/12/12'    100       120     250.7   Low  2020
13        60  '2020/12/13'    106       128     345.3   Low  2020
14        60  '2020/12/14'    104       132     379.3  High  2020
15        60  '2020/12/15'     98       123     275.0   Low  2020
16        60  '2020/12/16'     98       120     215.2   Low  2020
17        60  '2020/12/17'    100       120     300.0   Low  2020
18        45  '2020/12/18'     90       112       NaN   Low  2020
19        60  '2020/12/19'    103       123     323.0   Low  2020
20        45  '2020/12/20'     97       125     243.0   Low  2020
21        60  '2020/12/21'    108       131     364.2  High  2020
22        45           NaN    100       119     282.0   Low  2020
23        60  '2020/12/23'    130       101     300.0   Low  2020
24        45  '2020/12/24'    105       132     246.0  High  2020
25        60  '2020/12/25'    102       126     334.5   Low  2020
26        60      20201226    100       120     250.0   Low  2020
27        60  '2020/12/27'     92       118     241.0   Low  2020
28        60  '2020/12/28'    103       132       NaN  High  2020
29        60  '2020/12/29'    100       132     280.0  High  2020
30        60  '2020/12/30'    102       129     380.3   Low  2020
31        60  '2020/12/31'     92       115     243.0   Low  2020

## Menerapkan Grouping pada DataFrame

In [ ]:
df.head()

   Duration          Date  Pulse  Maxpulse  Calories Level  Year
0        60  '2020/12/01'    110       130     409.1   Low  2020
1        60  '2020/12/02'    117       145     479.0  High  2020
2        60  '2020/12/03'    103       135     340.0  High  2020
3        45  '2020/12/04'    109       175     282.4  High  2020
4        45  '2020/12/05'    117       148     406.0  High  2020

In [ ]:
df.groupby('Level')['Maxpulse'].agg(['mean', 'sum'])

             mean   sum
Level
High   139.384615  1812
Low    121.052632  2300

## Menerapkan Concatinating pada DataFrame

In [ ]:
df.head()

   Duration          Date  Pulse  Maxpulse  Calories Level  Year
0        60  '2020/12/01'    110       130     409.1   Low  2020
1        60  '2020/12/02'    117       145     479.0  High  2020
2        60  '2020/12/03'    103       135     340.0  High  2020
3        45  '2020/12/04'    109       175     282.4  High  2020
4        45  '2020/12/05'    117       148     406.0  High  2020

In [ ]:
add_df = pd.DataFrame({ 'Duration': [120, 130, 110],
                        'Date': ['2020/12/02', '2020/12/03', '2020/12/04'],
                        'Pulse': [110, 120, 130],
                        'Maxpulse': [135, 145, 175],
                        'Calories': [400.0, 420.0, 430.0],
                        'Level': ['Low', 'Low', 'High'],
                        'Year': [2020, 2020, 2020]})

In [ ]:
add_df

   Duration        Date  Pulse  Maxpulse  Calories Level  Year
0       120  2020/12/02    110       135     400.0   Low  2020
1       130  2020/12/03    120       145     420.0   Low  2020
2       110  2020/12/04    130       175     430.0  High  2020

In [ ]:
df.head()

   Duration          Date  Pulse  Maxpulse  Calories Level  Year
0        60  '2020/12/01'    110       130     409.1   Low  2020
1        60  '2020/12/02'    117       145     479.0  High  2020
2        60  '2020/12/03'    103       135     340.0  High  2020
3        45  '2020/12/04'    109       175     282.4  High  2020
4        45  '2020/12/05'    117       148     406.0  High  2020

In [ ]:
frames = [df, add_df]

new_df = pd.concat(frames, axis=0)

In [ ]:
new_df.tail()

    Duration          Date  Pulse  Maxpulse  Calories Level  Year
30        60  '2020/12/30'    102       129     380.3   Low  2020
31        60  '2020/12/31'     92       115     243.0   Low  2020
0        120    2020/12/02    110       135     400.0   Low  2020
1        130    2020/12/03    120       145     420.0   Low  2020
2        110    2020/12/04    130       175     430.0  High  2020

In [ ]:
more_df = pd.DataFrame({'Name': ['Angga', 'Mardadi', 'Rowi'],
                        'Domicile': ['Depok', 'Depok', 'Depok']})

In [ ]:
more_df

      Name Domicile
0    Angga    Depok
1  Mardadi    Depok
2     Rowi    Depok

In [ ]:
add_df

   Duration        Date  Pulse  Maxpulse  Calories Level  Year
0       120  2020/12/02    110       135     400.0   Low  2020
1       130  2020/12/03    120       145     420.0   Low  2020
2       110  2020/12/04    130       175     430.0  High  2020

In [ ]:
frames = [add_df, more_df]
new_df = pd.concat(frames, axis=1)

In [ ]:
new_df

,Duration,Date,Pulse,Maxpulse,Calories,Level,Year,Name,Domicile
0,120,2020/12/02,110,135,400.0,Low,2020,Angga,Depok
1,130,2020/12/03,120,145,420.0,Low,2020,Mardadi,Depok
2,110,2020/12/04,130,175,430.0,High,2020,Rowi,Depok

In [ ]:
add_df = pd.DataFrame({'ID': [1, 2, 3],
                       'Duration': [120, 130, 110],
                       'Date': ['2020/12/02', '2020/12/03', '2020/12/04'],
                       'Pulse': [110, 120, 130],
                       'Maxpulse': [135, 145, 175],
                       'Calories': [400.0, 420.0, 430.0],
                       'Level': ['Low', 'Low', 'High'],
                       'Year': [2020, 2020, 2020]})

more_df = pd.DataFrame({'ID': [3, 4, 5],
                        'Name': ['Angga', 'Mardadi', 'Rowi'],
                        'Domicile': ['Depok', 'Depok', 'Depok']})

In [ ]:
add_df

   ID  Duration        Date  Pulse  Maxpulse  Calories Level  Year
0   1       120  2020/12/02    110       135     400.0   Low  2020
1   2       130  2020/12/03    120       145     420.0   Low  2020
2   3       110  2020/12/04    130       175     430.0  High  2020

In [ ]:
more_df

   ID     Name Domicile
0   3    Angga    Depok
1   4  Mardadi    Depok
2   5     Rowi    Depok

In [ ]:
pd.merge(left=add_df, right=more_df, how='inner', on='ID')

,ID,Duration,Date,Pulse,Maxpulse,Calories,Level,Year,Name,Domicile
0,3,110,2020/12/04,130,175,430.0,High,2020,Angga,Depok

In [ ]:
pd.merge(left=add_df, right=more_df, how='outer', on='ID')

,ID,Duration,Date,Pulse,Maxpulse,Calories,Level,Year,Name,Domicile
0,1,120.0,2020/12/02,110.0,135.0,400.0,Low,2020.0,NaN,NaN
1,2,130.0,2020/12/03,120.0,145.0,420.0,Low,2020.0,NaN,NaN
2,3,110.0,2020/12/04,130.0,175.0,430.0,High,2020.0,Angga,Depok
3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mardadi,Depok
4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rowi,Depok

In [ ]:
pd.merge(left=add_df, right=more_df, how='left', on='ID')

,ID,Duration,Date,Pulse,Maxpulse,Calories,Level,Year,Name,Domicile
0,1,120,2020/12/02,110,135,400.0,Low,2020,NaN,NaN
1,2,130,2020/12/03,120,145,420.0,Low,2020,NaN,NaN
2,3,110,2020/12/04,130,175,430.0,High,2020,Angga,Depok

In [ ]:
pd.merge(left=add_df, right=more_df, how='right', on='ID')

,ID,Duration,Date,Pulse,Maxpulse,Calories,Level,Year,Name,Domicile
0,3,110.0,2020/12/04,130.0,175.0,430.0,High,2020.0,Angga,Depok
1,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mardadi,Depok
2,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rowi,Depok

## Menerapkan Saving pada DataFrame

In [ ]:
df.to_csv('./new_data.csv')

In [ ]:
df.to_csv('./new_data.csv', index=False)

## Mengatasi Missing Values dengan drop data

In [ ]:
pd.options.display.max_rows = 9999

In [ ]:
df = pd.read_csv('./dirty_data.csv')

In [ ]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
df.dropna(inplace=True)

In [ ]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

## Mengatasi Missing Values dengan nilai baru

In [ ]:
df = pd.read_csv('./dirty_data.csv')
df.fillna(100, inplace=True)

In [ ]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112     100.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           100    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132     100.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
df = pd.read_csv('./dirty_data.csv')
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
df['Calories'].fillna(100, inplace=True)

In [ ]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112     100.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132     100.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

## Mengatasi Missing Values dengan nilai mean

In [ ]:
df = pd.read_csv('./dirty_data.csv')
x = df['Calories'].mean()

In [ ]:
df['Calories'].fillna(x, inplace=True)

In [ ]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130    409.10
1         60  '2020/12/02'    117       145    479.00
2         60  '2020/12/03'    103       135    340.00
3         45  '2020/12/04'    109       175    282.40
4         45  '2020/12/05'    117       148    406.00
5         60  '2020/12/06'    102       127    300.00
6         60  '2020/12/07'    110       136    374.00
7        450  '2020/12/08'    104       134    253.30
8         30  '2020/12/09'    109       133    195.10
9         60  '2020/12/10'     98       124    269.00
10        60  '2020/12/11'    103       147    329.30
11        60  '2020/12/12'    100       120    250.70
12        60  '2020/12/12'    100       120    250.70
13        60  '2020/12/13'    106       128    345.30
14        60  '2020/12/14'    104       132    379.30
15        60  '2020/12/15'     98       123    275.00
16        60  '2020/12/16'     98       120    215.20
17        60  '2020/12/17'    100       120    300.00
18        45  '2020/12/18'     90       112    304.68
19        60  '2020/12/19'    103       123    323.00
20        45  '2020/12/20'     97       125    243.00
21        60  '2020/12/21'    108       131    364.20
22        45           NaN    100       119    282.00
23        60  '2020/12/23'    130       101    300.00
24        45  '2020/12/24'    105       132    246.00
25        60  '2020/12/25'    102       126    334.50
26        60      20201226    100       120    250.00
27        60  '2020/12/27'     92       118    241.00
28        60  '2020/12/28'    103       132    304.68
29        60  '2020/12/29'    100       132    280.00
30        60  '2020/12/30'    102       129    380.30
31        60  '2020/12/31'     92       115    243.00

## Mengatasi Missing Values dengan nilai median

In [ ]:
df = pd.read_csv('./dirty_data.csv')
x = df['Calories'].median()

In [ ]:
df['Calories'].fillna(x, inplace=True)

In [ ]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112     291.2
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132     291.2
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

## Mengatasi Missing Values dengan nilai mode

In [ ]:
df = pd.read_csv('./dirty_data.csv')
x = df['Calories'].mode()[0]

In [ ]:
df['Calories'].fillna(x, inplace=True)

In [ ]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132     300.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
df = pd.read_csv('./dirty_data.csv')
df.drop_duplicates(inplace=True)

In [ ]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

## Mengatasi Wrong Format dengan ubah format

In [ ]:
df = pd.read_csv('./dirty_data.csv')
df['Date'] = pd.to_datetime(df['Date'])

In [ ]:
df

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [ ]:
df['Calories'] = pd.to_numeric(df['Calories'])

In [ ]:
df

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [ ]:
df.dropna(subset=['Date'], inplace=True)

In [ ]:
df

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

## Mengatasi Wrong Data dengan ubah data

In [ ]:
df = pd.read_csv('./dirty_data.csv')
df.loc[7, 'Duration'] = 45

In [ ]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7         45  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
df = pd.read_csv('./dirty_data.csv')

for x in df.index:
    if df.loc[x, 'Duration'] > 120:
        df.loc[x, 'Duration'] = 120

## Mengatasi Wrong Data dengan drop data

In [ ]:
df = pd.read_csv('./dirty_data.csv')

In [ ]:
df.drop(7, inplace=True)

In [ ]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
df = pd.read_csv('./dirty_data.csv')
for x in df.index:
    if df.loc[x, 'Duration'] > 120:
        df.drop(x, inplace=True)

---

---